from panda_rl_env.envs.panda_tasks.panda_pick_and_place import PandaPickAndPlaceEnv
from panda_rl_env.envs.panda_tasks.panda_push import PandaPushEnv
from panda_rl_env.envs.panda_tasks.panda_reach import PandaReachEnv
from panda_rl_env.envs.panda_tasks.panda_slide import PandaSlideEnv
from panda_rl_env.envs.panda_tasks.panda_stack import PandaStackEnv
from panda_rl_env.envs.panda_tasks.panda_flip import PandaFlipEnv
from panda_rl_env.envs.panda_tasks.panda_reach2 import PandaReachEnv2